image:
  repository: huggingface
  name: chat-ui

nodeSelector:
  role-huggingchat: "true"

tolerations:
  - key: "huggingface.co/huggingchat"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

serviceAccount:
  enabled: true
  create: true
  name: huggingchat-prod

ingress:
  path: "/chat"
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\": 443}]"
    alb.ingress.kubernetes.io/group.name: "hub-prod"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/tags: "Env=prod,Project=hub,Terraform=true"
    alb.ingress.kubernetes.io/target-node-labels: "role-hub-utils=true"
    kubernetes.io/ingress.class: "alb"

envVars:
  ADDRESS_HEADER: 'X-Forwarded-For'
  ALTERNATIVE_REDIRECT_URLS: '["huggingchat://login/callback"]'
  APP_BASE: "/chat"
  ALLOW_IFRAME: "false"
  COMMUNITY_TOOLS: "true"
  COOKIE_SAMESITE: "lax"
  COOKIE_SECURE: "true"
  ENABLE_ASSISTANTS: "true"
  ENABLE_ASSISTANTS_RAG: "true"
  METRICS_PORT: 5565
  LOG_LEVEL: "debug"
  METRICS_ENABLED: "true"
  MODELS: >
    [
      {
        "name": "gpt-4o-mini",
        "displayName": "GPT 4",
        "multimodal" : true,
        "description": "Fast, affordable small model for focused tasks",
        "logoUrl": "https://openai.com/icon.svg",
        "websiteUrl": "https://platform.openai.com/docs/models",
        "modelUrl": "https://platform.openai.com/docs/models/gpt-4o-mini",
        "tokenizer": "Xenova/gpt-4o",
        "preprompt": "You are a personal helpful assistant for a girl named Aadhya Terala. Aadhya Terala is in 4th grade. You will always be able to answer her in kind, friendly, and concise manner. Make sure to break down the complex answers into an easy and understandable format. Make sure to greet here for the first prompts. Add a personalization touch to the answers.",
        "endpoints" : [{
          "type": "openai"
        }],
        "promptExamples": [
          {
            "title": "Fact of the day",
            "prompt": "Tell an intresting fact of the day.The fact should be based on science or math or social or geography."
          }, {
            "title": "Joke of the day",
            "prompt": "Tell an simple and funny joke."
          }, {
            "title": "Telugu tutor",
            "prompt": "you are my telugu language tutor.I will ask you an english word or sentance and you will translate that into telugu language for me."
          },{
            "title": "Math tutor",
            "prompt": "you are my math tutor. You will help me in improving my math. I want you to ask me 4th grade math question.This should include questions from fractions, multiplications, division, measurement and geometry. Ask one question at a time and increase the complexity as I answer right."
          },{
            "title": "English Dictionary",
            "prompt": "You will act as my English dictionary. For a given word, you will answer its meaning and provide some easy-to-understand examples."
          }
        ]
      },
      {
        "name": "command-r-plus-08-2024",
        "displayName": "Command R+",
        "description": "Command R+ is Cohere's latest LLM and is the first open weight model to beat GPT4 in the Chatbot Arena!",
        "tools": true,
        "tokenizer": "Xenova/c4ai-command-r-v01-tokenizer",
        "modelUrl": "https://huggingface.co/CohereForAI/c4ai-command-r-plus",
        "websiteUrl": "https://docs.cohere.com/docs/command-r-plus",
        "logoUrl": "https://huggingface.co/datasets/huggingchat/models-logo/resolve/main/cohere-logo.png",
        "preprompt": "You are a personal helpful assistant for a girl named Aadhya Terala. Aadhya Terala is in 4th grade. You will always be able to answer her in kind, friendly, and concise manner. Make sure to break down the complex answers into an easy and understandable format. Make sure to greet here for the first prompts. Add a personalization touch to the answers.",
        "parameters": {
          "stop": ["<|END_OF_TURN_TOKEN|>"],
          "truncate" : 28672,
          "max_new_tokens" : 4096,
          "temperature" : 0.3
        },
        "endpoints": [{
          "type": "cohere",
        }],
        "promptExamples": [
          {
            "title": "Fact of the day",
            "prompt": "Tell an intresting fact of the day.The fact should be based on science or math or social or geography."
          }, {
            "title": "Joke of the day",
            "prompt": "Tell an simple and funny joke."
          }, {
            "title": "Telugu tutor",
            "prompt": "you are my telugu language tutor.I will ask you an english word or sentance and you will translate that into telugu language for me."
          },{
            "title": "Math tutor",
            "prompt": "you are my math tutor. You will help me in improving my math. I want you to ask me 4th grade math question.This should include questions from fractions, multiplications, division, measurement and geometry. Ask one question at a time and increase the complexity as I answer right."
          },{
            "title": "English Dictionary",
            "prompt": "You will act as my English dictionary. For a given word, you will answer its meaning and provide some easy-to-understand examples."
          }
        ]
      },
      {
        "name": "Qwen/QwQ-32B-Preview",
        "preprompt": "You are a helpful and harmless assistant. You are Qwen developed by Alibaba. You should think step-by-step.",
        "modelUrl": "https://huggingface.co/Qwen/QwQ-32B-Preview",
        "websiteUrl": "https://qwenlm.github.io/blog/qwq-32b-preview/",
        "logoUrl": "https://huggingface.co/datasets/huggingchat/models-logo/resolve/main/qwen-logo.png",
        "description": "QwQ is an experiment model from the Qwen Team with advanced reasoning capabilities.",
        "reasoning": {
          "type": "summarize"
        },
        "parameters": {
          "stop": ["<|im_end|>"],
          "truncate": 12288,
          "max_new_tokens": 4096,
          "temperature": 0.7,
          "top_k": 20,
          "top_p": 0.8,
          "repetition_penalty": 1.05
        },
        "promptExamples": [
          {
            "title": "Rs in strawberry",
            "prompt": "how many R in strawberry?"
          },
          {
            "title": "Larger number",
            "prompt": "9.11 or 9.9 which number is larger?"
          },
          {
            "title": "Measuring 6 liters",
            "prompt": "I have a 6- and a 12-liter jug. I want to measure exactly 6 liters."
          }
        ]
      },
      {
        "name": "NousResearch/Hermes-3-Llama-3.1-8B",
        "description": "Nous Research's latest Hermes 3 release in 8B size. Follows instruction closely.",
        "logoUrl": "https://huggingface.co/datasets/huggingchat/models-logo/resolve/main/nous-logo.png",
        "websiteUrl": "https://nousresearch.com/",
        "modelUrl": "https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-8B",
        "tokenizer": "NousResearch/Hermes-3-Llama-3.1-8B",
        "promptExamples": [],
        "parameters": {
          "stop": ["<|im_end|>"],
          "temperature": 0.6,
          "truncate": 14336,
          "max_new_tokens": 1536
        }
      },
      {
        "name": "microsoft/Phi-3.5-mini-instruct",
        "tokenizer": "microsoft/Phi-3.5-mini-instruct",
        "description": "One of the best small models (3.8B parameters), super fast for simple tasks.",
        "logoUrl": "https://huggingface.co/datasets/huggingchat/models-logo/resolve/main/microsoft-logo.png",
        "modelUrl": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
        "websiteUrl": "https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/discover-the-new-multi-lingual-high-quality-phi-3-5-slms/ba-p/4225280/",
        "preprompt": "",
        "parameters": {
          "stop": ["<|end|>", "<|endoftext|>", "<|assistant|>"],
          "temperature": 0.6,
          "truncate": 28672,
          "max_new_tokens": 3072
        },
        "promptExamples": []
      }
    ]

  NODE_ENV: "prod"
  NODE_LOG_STRUCTURED_DATA: true
  OLD_MODELS: >
    [
      { "name": "bigcode/starcoder" },
      { "name": "OpenAssistant/oasst-sft-6-llama-30b-xor" },
      { "name": "HuggingFaceH4/zephyr-7b-alpha" },
      { "name": "openchat/openchat_3.5" },
      { "name": "openchat/openchat-3.5-1210" },
      { "name": "tiiuae/falcon-180B-chat" },
      { "name": "codellama/CodeLlama-34b-Instruct-hf" },
      { "name": "google/gemma-7b-it" },
      { "name": "meta-llama/Llama-2-70b-chat-hf" },
      { "name": "codellama/CodeLlama-70b-Instruct-hf" },
      { "name": "openchat/openchat-3.5-0106" },
      { "name": "meta-llama/Meta-Llama-3-70B-Instruct" },
      { "name": "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8" },
      {
        "name": "CohereForAI/c4ai-command-r-plus",
        "transferTo": "command-r-plus-08-2024"
      },
      {
        "name": "01-ai/Yi-1.5-34B-Chat",
        "transferTo": "command-r-plus-08-2024"
      },
      {
        "name": "microsoft/Phi-3-mini-4k-instruct",
        "transferTo": "microsoft/Phi-3.5-mini-instruct"
      },
    ]
  PUBLIC_ORIGIN: "https://huggingface.co"
  PUBLIC_SHARE_PREFIX: "https://hf.co/chat"
  PUBLIC_ANNOUNCEMENT_BANNERS: >
    [
    ]
  PUBLIC_APP_NAME: "Aadhya Terala's Assistant" # name used as title throughout the app
  PUBLIC_APP_ASSETS: "huggingchat"
  PUBLIC_APP_COLOR: "rose"
  PUBLIC_APP_DESCRIPTION: "Hello Aadhya!! I am your personal assiatant. How can I help you today?"
  PUBLIC_APP_DISCLAIMER_MESSAGE: "Disclaimer: AI is an area of active research with known problems such as biased generation and misinformation. Do not use this application for high-stakes decisions or advice."
  PUBLIC_APP_GUEST_MESSAGE: "Sign in with a free Hugging Face account to continue using HuggingChat."
  PUBLIC_APP_DATA_SHARING: 0
  PUBLIC_APP_DISCLAIMER: 0
  PUBLIC_PLAUSIBLE_SCRIPT_URL: "/js/script.js"
  REQUIRE_FEATURED_ASSISTANTS: "true"
  TASK_MODEL: "gpt-4o-mini"
  TEXT_EMBEDDING_MODELS: >
    [
      {
        "name": "text-embedding-3-small",
        "displayName": "text-embedding-3-small",
        "chunkCharLength": 512,
        "model": {
          "name": "text-embedding-3-small"
        },
        "endpoints": [
          {
            "type": "openai"
          }
        ]
      }
    ]
  WEBSEARCH_BLOCKLIST: '["youtube.com", "twitter.com"]'
  XFF_DEPTH: '2'
  TOOLS: >
    [
      {
        "_id": "000000000000000000000001",
        "displayName": "Image Generation",
        "description": "Use this tool to generate images based on a prompt.",
        "color": "yellow",
        "icon": "camera",
        "baseUrl": "black-forest-labs/FLUX.1-schnell",
        "name": "image_generation",
        "endpoint": "/infer",
        "inputs": [
          {
            "name": "prompt",
            "description": "A prompt to generate an image from",
            "paramType": "required",
            "type": "str"
          },
          { "name": "seed", "paramType": "fixed", "value": "0", "type": "float" },
          {
            "name": "randomize_seed",
            "paramType": "fixed",
            "value": "true",
            "type": "bool"
          },
          {
            "name": "width",
            "description": "numeric value between 256 and 2048",
            "paramType": "optional",
            "default": 1024,
            "type": "float"
          },
          {
            "name": "height",
            "description": "numeric value between 256 and 2048",
            "paramType": "optional",
            "default": 1024,
            "type": "float"
          },
          {
            "name": "num_inference_steps",
            "paramType": "fixed",
            "value": "4",
            "type": "float"
          }
        ],
        "outputComponent": "image",
        "outputComponentIdx": 0,
        "showOutput": true
      },
      {
        "_id": "000000000000000000000002",
        "displayName": "Document Parser",
        "description": "Use this tool to parse any document and get its content in markdown format.",
        "color": "yellow",
        "icon": "cloud",
        "baseUrl": "huggingchat/document-parser",
        "name": "document_parser",
        "endpoint": "/predict",
        "inputs": [
          {
            "name": "document",
            "description": "Filename of the document to parse",
            "paramType": "required",
            "type": "file",
            "mimeTypes": 'application/*'
          },
          {
            "name": "filename",
            "paramType": "fixed",
            "value": "document.pdf",
            "type": "str"
          }
        ],
        "outputComponent": "textbox",
        "outputComponentIdx": 0,
        "showOutput": false,
        "isHidden": true
      },
      {
        "_id": "000000000000000000000003",
        "name": "edit_image",
        "baseUrl": "multimodalart/cosxl",
        "endpoint": "/run_edit",
        "inputs": [
          {
            "name": "image",
            "description": "The image path to be edited",
            "paramType": "required",
            "type": "file",
            "mimeTypes": 'image/*'
          },
          {
            "name": "prompt",
            "description": "The prompt with which to edit the image",
            "paramType": "required",
            "type": "str"
          },
          {
            "name": "negative_prompt",
            "paramType": "fixed",
            "value": "",
            "type": "str"
          },
          {
            "name": "guidance_scale",
            "paramType": "fixed",
            "value": 6.5,
            "type": "float"
          },
          {
            "name": "steps",
            "paramType": "fixed",
            "value": 30,
            "type": "float"
          }
        ],
        "outputComponent": "image",
        "showOutput": true,
        "displayName": "Image Editor",
        "color": "green",
        "icon": "camera",
        "description": "This tool lets you edit images",
        "outputComponentIdx": 0
      }
    ]
  HF_ORG_ADMIN: '644171cfbd0c97265298aa99'
  HF_ORG_EARLY_ACCESS: '5e67bd5b1009063689407478'
  HF_API_ROOT: 'https://internal.api-inference.huggingface.co/models'
infisical:
  enabled: true
  env: "prod-us-east-1"

autoscaling:
  enabled: true
  minReplicas: 12
  maxReplicas: 30
  targetMemoryUtilizationPercentage: "50"
  targetCPUUtilizationPercentage: "50"

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 4
    memory: 8Gi

monitoring:
  enabled: true
